title: Wei He
position: Research Student
affiliation: HKUST(GZ)
email: wei.he1024@gmail.com
keywords: Wei He
google_scholar:
github_link:
linkedin: 
avatar: 
google_analytics: 
favicon: 
favicon_dark: 
description: 
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light