title: Wei He
position: M.Phil Student
affiliation: Hong Kong University of Science and Technology (Guangzhou)
email: wei.he1024@gmail.com
keywords: Wei He
google_scholar:
github_link:
linkedin: 
avatar: 
google_analytics: 
favicon: 
favicon_dark: 
description: 
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light