title: Wei He
position: PhD Student
affiliation: HKUST(GZ)
email: whe694@connect.hkust-gz.edu.cn
keywords: Wei He
google_scholar:
github_link:
linkedin: 
avatar: ./assets/img/avatar.jpg
google_analytics: 
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon.png
description: 
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light